name       : neverball
version    : 1.6.0
release    : 2
source     :
    - https://neverball.org/neverball-1.6.0.tar.gz : 73fe63cca4f96e2d355480d03bc0b2904e83a0abdf65fe8c52db5cc3cca88fa0
license    : GPL-2.0-or-later
component  : games.arcade
summary    : Neverball - Tilt the floor to roll a ball through an obstacle course within the given time
description: |
    Neverball - Tilt the floor to roll a ball through an obstacle course within the given time.
builddeps  :
    - pkgconfig(SDL2_ttf)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(physfs)
    - pkgconfig(vorbis)
build      : |
    %make DATADIR=/usr/share/neverball LOCALEDIR=/usr/share/locale
install    : |
    install -d -m 00644 $installdir/usr/bin
    install -m 00755 neverball neverputt mapc $installdir/usr/bin

    install -d -m 00644 $installdir/usr/share/applications
    install -m 00644 dist/*.desktop $installdir/usr/share/applications

    install -d -m 00644 $installdir/usr/share/doc/neverball
    cp -R doc/* $installdir/usr/share/doc/neverball
    chmod 00644 -R $installdir/usr/share/doc/neverball

    install -d -m 00644 $installdir/usr/share/icons/hicolor
    for i in 16 24 32 48 64 128 256 512; do
        install -D -m644 dist/neverball_$i.png "$installdir/usr/share/icons/hicolor/${i}x$i/apps/neverball.png"
        install -D -m644 dist/neverputt_$i.png "$installdir/usr/share/icons/hicolor/${i}x$i/apps/neverputt.png"
    done

    install -d -m 00644 $installdir/usr/share/locale
    cp -R locale/* $installdir/usr/share/locale
    chmod 00644 -R $installdir/usr/share/locale

    install -d -m 00644 $installdir/usr/share/man/man1
    install -m 00644 dist/mapc.1 $installdir/usr/share/man/man1

    install -d -m 00644 $installdir/usr/share/man/man6
    install -m 00644 dist/neverball.6 $installdir/usr/share/man/man6
    install -m 00644 dist/neverputt.6 $installdir/usr/share/man/man6

    install -d -m 00644 $installdir/usr/share/neverball
    cp -R data/* $installdir/usr/share/neverball
    chmod 00755 -R $installdir/usr/share/neverball
